group: message.digi.dev
image: jamsheedmistri/emqx.v1.message.digi.dev:latest
imagepull: Always
kind: Emqx
mounter: false
name: emqx
namespace: default
plural: emqxes
version: v1
persistent_volume:
  path: {{home}}/.digi/pv/emqx/
  size: 100Mi
